import { Montserrat } from 'next/font/google'
import './globals.css'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Notes app!',
  description: 'Generated by create next app',
}

export default function Layout({ children }) {
  return (
    <html>
      <head>        
      <link href="https://cdn.jsdelivr.net/npm/daisyui@4.4.24/dist/full.min.css" rel="stylesheet" type="text/css" />
      <script src="https://cdn.tailwindcss.com" defer></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
